[main]
name = "kaiagotchi"
lang = "en"
iface = "wlan0mon"
mon_start_cmd = "/usr/bin/monstart"
mon_stop_cmd = "/usr/bin/monstop"
mon_max_blind_epochs = 5
no_restart = false
whitelist = [
    "EXAMPLE_NETWORK",
    "ANOTHER_EXAMPLE_NETWORK",
    "fo:od:ba:be:fo:od",
    "fo:od:ba"
]
confd = "/etc/pwnagotchi/conf.d/"
custom_plugin_repos = [
    "https://github.com/jayofelony/pwnagotchi-torch-plugins/archive/master.zip",
    "https://github.com/Sniffleupagus/pwnagotchi_plugins/archive/master.zip",
    "https://github.com/NeonLightning/pwny/archive/master.zip",
    "https://github.com/wpa-2/Pwnagotchi-Plugins/archive/master.zip",
    "https://github.com/cyberartemio/wardriver-pwnagotchi-plugin/archive/main.zip"
]
custom_plugins = "/usr/local/share/kaiagotchi/custom-plugins/" # Corrected path

[main.plugins.auto-tune]
enabled = true

[main.plugins.auto_backup]
enabled = false
interval = "daily"  
max_tries = 0
backup_location = "/home/kaia/" # Changed from /home/pi/
files = [
    "/root/settings.yaml",
    "/root/client_secrets.json",
    "/root/.api-report.json",
    "/root/.ssh",
    "/root/.bashrc",
    "/root/.profile",
    "/home/kaia/handshakes", # Changed from /home/pi/
    "/root/peers",
    "/etc/kaiagotchi/", # Changed path
    "/usr/local/share/kaiagotchi/custom-plugins", # Changed path
    "/etc/ssh/",
    "/home/kaia/.bashrc", # Changed from /home/pi/
    "/home/kaia/.profile", # Changed from /home/pi/
    "/home/kaia/.wpa_sec_uploads" # Changed from /home/pi/
]
exclude = [ "/etc/kaiagotchi/logs/*"] # Changed path
commands = [ "tar cf {backup_file} {files}"]

[main.plugins.auto-update]
enabled = true
install = true
interval = 1
token = "" 

[main.plugins.bt-tether]
enabled = false # DISABLED: Hardware-dependent

[main.plugins.fix_services]
enabled = true

[main.plugins.cache]
enabled = true

[main.plugins.gdrivesync]
enabled = false
backupfiles = [""]
backup_folder = "KaiagotchiBackups" # Naming consistency
interval = 1

[main.plugins.gpio_buttons]
enabled = false # DISABLED: Hardware-dependent

[main.plugins.gps]
enabled = false # DISABLED: Hardware-dependent
speed = 19200
device = "/dev/null" # Nullified hardware path

[main.plugins.gps_listener]
enabled = false # DISABLED: Hardware-dependent

[main.plugins.grid]
enabled = true
report = true

[main.plugins.logtail]
enabled = false
max-lines = 10000

[main.plugins.memtemp]
enabled = false # DISABLED: Hardware-dependent

[main.plugins.ohcapi]
enabled = false

[main.plugins.pwndroid]
enabled = false

[main.plugins.pisugarx]
enabled = false # DISABLED: Hardware-dependent

[main.plugins.pwncrack]
enabled = false
key = ""

[main.plugins.session-stats]
enabled = false
save_directory = "/var/tmp/kaiagotchi/sessions/" # Changed path

[main.plugins.ups_hat_c]
enabled = false # DISABLED: Hardware-dependent

[main.plugins.ups_lite]
enabled = false # DISABLED: Hardware-dependent

[main.plugins.webcfg]
enabled = true

[main.plugins.webgpsmap]
enabled = false

[main.plugins.wigle]
enabled = false

[main.plugins.wpa-sec]
enabled = false
api_key = ""
api_url = "https://wpa-sec.stanev.org"
download_results = false
show_pwd = false
single_files = false

[main.log]
path = "/etc/kaiagotchi/log/kaiagotchi.log" # Changed path
path-debug = "/etc/kaiagotchi/log/kaiagotchi-debug.log" # Changed path

[main.log.rotation]
enabled = true
size = "10M"

[personality]
advertise = true
deauth = true
associate = true
channels = []
min_rssi = -200
ap_ttl = 120
sta_ttl = 300
recon_time = 30
max_inactive_scale = 2
recon_inactive_multiplier = 2
hop_recon_time = 10
min_recon_time = 5
max_interactions = 3
max_misses_for_recon = 5
excited_num_epochs = 10
bored_num_epochs = 15
sad_num_epochs = 25
bond_encounters_factor = 20000
throttle_a = 0.4
throttle_d = 0.9

[ui]
invert = false
cursor = true
fps = 0.0

[ui.font]
name = "DejaVuSansMono"
size_offset = 0

[ui.faces]
look_r = "( ⚆_⚆)"
look_l = "(☉_☉ )"
look_r_happy = "( ◕‿◕)"
look_l_happy = "(◕‿◕ )"
sleep = "(⇀‿‿↼)"
sleep2 = "(≖‿‿≖)"
awake = "(◕‿‿◕)"
bored = "(-__-)"
intense = "(°▃▃°)"
cool = "(⌐■_■)"
happy = "(•‿‿•)"
excited = "(ᵔ◡◡ᵔ)"
grateful = "(^‿‿^)"
motivated = "(☼‿‿☼)"
demotivated = "(≖__≖)"
smart = "(✜‿‿✜)"
lonely = "(ب__ب)"
sad = "(╥☁╥ )"
angry = "(-_-')"
friend = "(♥‿‿♥)"
broken = "(☓‿‿☓)"
debug = "(#__#)"
upload = "(1__0)"
upload1 = "(1__1)"
upload2 = "(0__1)"
png = false
position_x = 0
position_y = 34

[ui.web]
enabled = true
address = "::"
auth = false
username = "changeme"
password = "changeme"
origin = ""
port = 8080
on_frame = ""

[ui.display]
enabled = false # FORCED HEADLESS MODE
rotation = 0 # No rotation needed for headless
type = "dummydisplay" # FORCED DUMMY DISPLAY

[bettercap]
handshakes = "/home/kaia/handshakes" # Changed path
silence = [
    "ble.device.new",
    "ble.device.lost",
    "ble.device.service.discovered",
    "ble.device.characteristic.discovered",
    "ble.device.disconnected",
    "ble.device.connected",
    "ble.connection.timeout",
    "wifi.client.new",
    "wifi.client.lost",
    "wifi.client.probe",
    "wifi.ap.new",
    "wifi.ap.lost",
    "mod.started"
]

[fs.memory]
enabled = true

[fs.memory.mounts.log]
enabled = true
mount = "/etc/kaiagotchi/log/" # Changed path
size = "50M"
sync = 60
zram = true
rsync = true

[fs.memory.mounts.data]
enabled = true
mount = "/var/tmp/kaiagotchi" # Changed path
size = "10M"
sync = 3600
zram = true
rsync = true